config/routes.rb
IdejuAkademija::Application.routes.draw do

  post "invitations", controller: :invitations, action: :create
  post "/paypal-notifications" => "static#paypal_notifications"

  get "/pay-with-paypal/:id" => "payments_gateway#pay_with_paypal", :as => :pay_with_paypal
  get "/user_payment_notifications" => "static#user_payment_notifications", :as => :pay_with_paypal

  get "test/new_request"
  #User devise auth
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "sessions"} do
     # get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  # Administration
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Authentifications => test page
  get "/login" => "static#login", :as => :login
  get "/logout" => "static#logout", :as => :logout

  #=> Login
  namespace :login do
    get "draugiem/auth", :as => :draugiem_auth
    get "draugiem/callback"
    get "draugiem/iframe"
    post "facebook/auth", :as => :facebook_auth
    get "facebook/callback"
    get "synchronize/create/:name" => "synchronize#create", :as => :synchronization
    get "synchronize/destroy/:id" => "synchronize#destroy", :as => :desynchronization
  end

  # API
  namespace :api do
    match "sidebar_messages" => "sidebar_messages#for_current_user", :as => :sidebar_messages_for_current_user
    match "mark_bubble_as_seen/:id/:user_id" => "sidebar_messages#mark_as_seen", :as => :sidebar_messages_seen

    resources :categories
    resources :facebook_categories, :only => :index
    resources :contest_requests
    resources :crowdsourced_contests, :only => [:create, :update, :show, :index] do
      resources :crowdsourcing_results, :only => [:index] do

      end
    end

    #=> Contest
    resources :contests do
      collection do
        post "upload_image"
        get "root"
        get "root_in_categories"
      end

      resources :crowdsourcing_results, :only => [:index] do
        collection do
          get 'get_from_facebook'
        end
      end

      #=> Ideas
      resources :ideas do
        collection do
          match "vote/:first_idea_id/:second_idea_id(/:selected_idea_id)" => "ideas#vote", :as => :vote
          match "show_duel" => "ideas#show_duel", :as => :show_duel
        end

        member do
          get "report_spam" => "ideas#report_spam", :as => :report_spam
        end
      end

      resources :tmp_ideas do
        collection do
          match "vote/:first_idea_id/:second_idea_id(/:selected_idea_id)" => "tmp_ideas#vote", :as => :vote
          match "show_duel" => "tmp_ideas#show_duel", :as => :show_duel
        end

        member do
          get "report_spam" => "ideas#report_spam", :as => :report_spam
        end
      end
    end

    resources :payment_transactions, :only => :show
    resources :payments , :only => [:index, :create] do
      collection do
        get 'update_transaction'
      end
    end

    resources :translations

     #=> Statistic
    resources :statistics do
      collection do
        match "contest_users/:contest_id(/:user_id)" => "statistics#contest_users", :as => :contest_users
        match "contest_ideas/:contest_id(/:user_id)" => "statistics#contest_ideas", :as => :contest_ideas
        match "contest_room/:contest_id(/:user_id)" => "statistics#contest_room", :as => :contest_room
        match "contest_user_ideas/:contest_id(/:user_id)" => "statistics#contest_user_ideas", :as => :contest_user_ideas
        match "user/:user_id(/:category_id)" => "statistics#user", :as => :user
        match "tmp_user/:tmp_user_id(/:category_id)" => "statistics#tmp_user", :as => :tmp_user
        match "tmp_user_single_update/:user_id/:category_id" => "statistics#tmp_user_single_update", :as => :tmp_user_signle_update
        match "user_update/:user_id" => "statistics#user_update", :as => :user_update
        match "user_single_update/:user_id/:category_id" => "statistics#user_single_update", :as => :user_single_update
        match "user_profile(/:user_id)" => "statistics#user_profile", :as => :user_profile
        match "category_users/:category_id(/:users_page)" => "statistics#category_users", :as => :category_users
        match "contest_end_results/:contest_id" => "statistics#contest_end_results", :as => :contest_end_results
      end
    end

    #=> Logs
    resources :logs do
      collection do
        match "user/:user_id(/:timestamp)" => "logs#user", :as => :user_logs
      end
    end

    # => Popups
    match "popups/:user_id(/:popup_id)" => "popups#user", :as => :user_popups
    match "tmp_popups/:user_id(/:popup_id)" => "popups#tmp_user", :as => :tmp_user_popups

    # => Contact Form
    post "contact_form/create"

    # => Users
    resources :users do
      collection do
        get "current"
        match ":id/update_image" => "users#update_image", :as => :update_image
        get "check_out_money"
        post "check_out_money"
        match "update_category_notifications" => "users#update_category_notifications", :as => :update_category_notifications
        get "recent_badges"
      end
      member do
        get "top_ideas/:count" => "users#top_ideas"
        get "portfolio_ideas"
      end
    end

    # => TmpUsers
    resources :tmp_users do
      collection do
        get "current"
      end
    end

    # Admin messages
    resources :admin_messages, only: [:create]
  end

  resources :done_statistics

  get "update/category_users_statistic"
  get "server_time" => "main#time"

  #Internal app pages
  get "internal" => "internal#home", :as => :home_internal
  get "internal/about" => "internal#product", :as => :product_internal
  get "internal/faq" => "internal#faq", :as => :faq_internal
  get "internal/testimonials" => "internal#testimonials", :as => :testimonials_internal
  get "internal/pricing" => "internal#pricing", :as => :pricing_internal
  get "internal/thanks_for_payment" => "internal#thanks_for_payment", :as => :thanks_for_payment

  #Static (psd 2 html)
  scope "static" do
    get "/welcome" => "static#welcome", :as => :welcome
    get "/thanks_for_payment" => "static#thanks_for_payment", :as => :public_thanks_for_payment

    get "/test/:contest_id" => "static#test"

    get "/update_status/:contest_id" => "static#update_status", :as => :update_status
    get "/update_statistic" => "static#update_statistic", :as => :update_statistic

    get "/update_null_points" => "static#update_null_points", :as => :update_null_points

    get "/contest/guest" => "static#contest_guest", :as => :contest_guest
    get "/contest" => "static#contest", :as => :contest
    get "/contest/new" => "static#contest_new", :as => :new_contest
    get "/results" => "static#contest_results", :as => :contest_results
    get "/statistics" => "static#contest_statistics", :as => :contest_statistics

    get "/profile" => "static#profile", :as => :profile
    get "/profile/edit" => "static#profile_edit", :as => :profile_edit

    get "/popup" => "static#popup", :as => :popup
    get "/popup/tos" => "static#popup_tos", :as => :popup_tos
    get "/popup/default" => "static#popup_default", :as => :popup_default

    get "/popup/profile_edit_image" => "static#popup_profile_edit_image", :as => :popup_profile_edit_image

    get "/popup/welcome" => "static#popup_welcome", :as => :popup_welcome
    get "/popup/money" => "static#popup_money", :as => :popup_money
    get "/popup/first_points" => "static#popup_first_points", :as => :popup_first_points
    get "/popup/ten_points" => "static#popup_ten_points", :as => :popup_ten_points
    get "/popup/other_themes" => "static#popup_other_themes", :as => :popup_other_themes
    get "/popup/social" => "static#popup_social", :as => :popup_social
    get "/popup/earn_more" => "static#popup_earn_more", :as => :popup_earn_more
    get "/popup/first_achievement" => "static#popup_first_achievement", :as => :popup_first_achievement
    get "/popup/achievement" => "static#popup_achievement", :as => :popup_achievement
    get "/popup/like_idea" => "static#popup_like_idea", :as => :popup_like_idea
  end

  #Root path
  match '/blocked' => 'main#blocked', :as => 'blocked'
  root :to => "main#index", :as => :root
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
  
  #MENU_ACTIONS = %w( home product faq testimonials pricing )
  MENU_ACTIONS = %w( home product faq pricing )

  def home
  end

  def product
  end

  def faq
  end

  def testimonials
  end

  def pricing
    @services = Service.organization
  end

  def thanks_for_payment
    
  end
end

app/helpers/internal_helper.rb
module InternalHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def is_active?(action)
    "active" if send(:"#{action}_internal_url") == request.url
  end

  def facebook_app_link
    FACEBOOK_CONF[:omni_auth_full_host_path]
  end
end

app/views/internal/faq.html.haml
%h1= I18n.t "internal.faq.title", default: "FAQ"
#faq
  = I18n.t "internal.faq.content", default: "<div class='faq'><div class='question'><span>Q.</span>Question</div><div class='answer'><span>A.</span>Answer</div></div>"

app/views/internal/home.html.haml
%div#advert-top{ style: 'display: block !important;' }
  .ampersand
  .left
    = t "internal.advert_top.left.text", default: "<strong>200</strong> ideas in <strong>3</strong> days<br> from Your employees"
  .right
    = t "internal.advert_top.right.text", default: "Free access to <strong>thousands</strong><br> of creatives any moment"
  .clear
  #advert-top-image
    = image_tag "internal/employees.png", :class => "employees"
    = image_tag "internal/creatives.png", :class => "creatives"
    = image_tag "internal/left_arrow.png", :class => "left-arrow"
    = image_tag "internal/right_arrow.png", :class => "right-arrow"
    = image_tag "internal/bulbs.png", :class => "bulbs"
  = link_to "See it live!", AppUtils.public_page, :class => "orange-button"
#advert-middle
  .left
    = t "internal.advert_middle.left.text", default: "Brainstorming application with game<br>mechanics as an internal communication tool"
    = image_tag "internal/internal_screenshot.png"
  .right
    = t "internal.advert_middle.right.text", default: "Crowdsource any task for free and immediately<br>in a public Facebook application"
    = image_tag "internal/facebook_screenshot.png"
  = image_tag "internal/gears.png", :class => "gears"
#play-now
  = link_to t("internal.play_now.button_text", default: "Try now - it's free!"), new_user_registration_path, :class => "orange-button"
  %p= t "internal.play_now.description", default: "Innovative, effective and fun way to get the best ideas and information from your employees and co-workers. Use it for brainstorming, collecting data, analysing information, predicting future scenarios etc. Easiest, fastest and the most effective way to crowdsource your tasks and use the vast talent pool. <br>Just one click!"
  
- unless AppUtils.production_env?
  #social-buttons
    %a{:href => "https://twitter.com/share", :class => "twitter-share-button", :"data-url" => root_url, :"data-text" => "#{t "internal.share.twitter_text", default: "Everything starts with an idea"}"} Tweet
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="http://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    %iframe.facebook{:src => raw("http://www.facebook.com/plugins/like.php?href=#{CGI.escape root_url}&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=215446828545096"), :scrolling => "no", :frameborder => "0", :style => "border:none; overflow:hidden;", :"allowTransparency" => "true"}

app/views/internal/pricing.html.haml
%h1= I18n.t "internal.pricing.title", default: "Choose your plan!"
%p= I18n.t "internal.pricing.paragraph1", default: "If you are a new user, please apply for Free Trial. We offer three options of application.  For more information Contact Us.<ul><li>First one is the smallest one and it works only as a internal brainstorming tool for small teams.</li><li>Second one is Web based application that is accessible through this web page. You pay monthly fee that depends on the number of application users.</li><li>Third option is to obtain application and install it in your own companies’ intranet.  You pay the price and, starting with next year,  500$ USD/year for technical support. Your company can order custom design for application as an added bonus.</li></ul>"
#pricing
  %table
    %thead
      %tr
        %td= I18n.t "internal.pricing.table.thead.version", default: "Version"
        %td= I18n.t "internal.pricing.table.thead.users", default: "Users"
        %td= I18n.t "internal.pricing.table.thead.crowdsourcing_option", default: "Crowdsourcing option"
        %td= I18n.t "internal.pricing.table.thead.web_intranet", default: "Web/Intranet"
        %td= I18n.t "internal.pricing.table.thead.design", default: "Design"
        %td= I18n.t "internal.pricing.table.thead.price", default: "Price"
        %td= I18n.t "internal.pricing.table.thead.duration", default: "Duration"
        %td
    %tbody
      - @services.each do |service|
        %tr
          %td.name= t service.name, default: ( service.name.split(".")[-2] || service.name ).capitalize
          %td
            - if service.user_limit == 0
              = t "internal.pricing.table.user_limit.unlimited", default: "Unlimited"
            - else
              = t "internal.pricing.table.user_limit.upto", default: "Up to "
              = service.user_limit
          %td
            - if service.crowdsourcing?
              = image_tag "internal/crowdsourcing_true.png"
            - else
              = image_tag "internal/crowdsourcing_false.png"
          %td
            - if service.intranet?
              = t "internal.pricing.table.intranet", default: "Intranet"
            - else 
              = t "internal.pricing.table.web", default: "Web"
          %td
            - if service.unique_design?
              = t "internal.pricing.table.unique_design", default: "Unique"
            - else
              = t "internal.pricing.table.standard_design", default: "Standard"
          %td
            = "#{service.price_in('USD')} $"
          %td
            = service_duration service
          %td
            = link_to t("internal.pricing.table.buy", default: "Get it now"), paypal_url(service), :class => "buy"

app/views/internal/product.html.haml
%h1= I18n.t "internal.about.title.academy_of_ideas", default: "“Academy of Ideas”"
%p= I18n.t "internal.about.content.academy_of_ideas", default: "It is web based application that has proved itself as a very effective and exciting tool to fully access and use creative ant intellectual power within your company.  It is a perfect brainstorming tool that can be used to collect ideas, information, analysis, solutions and even make decisions. It is accessible to anyone at anytime anywhere.<br><br> <strong>Give your employees a chance to reveal their talents and showcase their knowledge in a exciting way!</strong>"

%h2= I18n.t "internal.about.title.history_and_achievements", default: "History and achievements"
%p= I18n.t "internal.about.content.history_and_achievements", default: "First prototype of application was created at the beginning of 2011 and launched in Facebook.  It was designed as a place where people would create ideas to real business and social challenges by using game mechanics.  During one year there have been posted 120 challenges from around 40 companies and organizations and more than 20 000 ideas have been created. 30-200 users participated in each challenge.  Challenges where very different in nature, but most of them where related to creating ideas for new products and improvement of current ones, marketing ideas, recipes, slogans, titles and  ideas for new events.  Prototype has been used successfully by government of Latvia, local municipalities, top Latvian companies, many small and medium companies as well as NGO."

%h2= I18n.t "internal.about.title.game_mechanics", default: "Game mechanics"
%p= I18n.t "internal.about.content.game_mechanics", default: "Application proved that its game mechanics can unleash people creativity and motivates them to participate, because players gain satisfaction from the process itself. Story of the game is that there is Academy of Ideas where players earn points and degrees in the Science of Ideas. They can reach PhD., Mag., professor degrees or even receive Nobel Prize in the Science of Ideas.  Players create ideas and vote for them by deciding winners of ideas’ duels. For every vote player receives 1 point and author of the winning idea receives 2 points.  There are filters that elevate best ideas during the course of the competition. Accordingly best ideas are being promoted and new ideas need to compete with better and better ideas in order to earn points. On average one challenge lasts 2-5 days and after that there is a summary of voting results, which can be used as an added feature for picking out best ideas that are going to be implemented.  The essential necessity for feedback to authors of ideas is being provided instantly by the voting of others players."

%h2= I18n.t "internal.about.title.features", default: "Features"
%p= I18n.t "internal.about.content.features", default: "Application can theoretically contain unlimited number of users and active challenges.  Application has up to 6 categories that can be used to separate different tasks or participants. For example there can be such categories as „Innovation”, „Marketing”, „Analysis” „Competition” etc.  There can be created many small rooms where users in small closed groups create ideas.  There can be created text, design and video challenges and, thus, ideas.  Each internal application is serviced by respective administrator/s, who insert challenges, invite and delete users, moderate whole process and crowdsource challenges to public version."

%h2= I18n.t "internal.about.title.facebook_connection", default: "Connection with public version in Facebook"
%p= I18n.t "internal.about.content.facebook_connection", default: "Every internal application with at least 50 users has an option to crowdsource for free challenges to public version of “Academy of Ideas” in Facebook.  In order to additionally motivate players, company can choose to stimulate monetary them by providing prize of at least 25$ that will be distributed between authors of best ideas.  Users of public version have agreed to voluntarily share their ideas and do not have any copyrights. Companies do not obtain copyrights to ideas through receiving them from public version, but companies can use those ideas in their own business and, if necessary, look for ways how to obtain copyrights."

%h2= I18n.t "internal.about.title.options", default: "Options how to use Academy of ideas"
%ul= I18n.t "internal.about.content.options", default: "<li>Can be used only as an internal communication tool</li><li>Can be used only as crowdsourcing tool </li><li>Can be used as internal communication tool and crowdsourcing tool at the same time</li><li>Can be used as a tool through which certain workers crowdsource basic tasks in order to focus energy and time on tasks with higher added value.</li>"

app/views/internal/testimonials.html.haml
%h1= I18n.t "internal.testimonials.title", default: "What others say about us?:"
#testimonials
  - 3.times do
    .testimonial
      .author
        = image_tag "http://placehold.it/96/96"
        .name
          Name Surname
          %br
          Place
      = "Text"

app/views/internal/thanks_for_payment.html.haml
<p> Thank you for Your payment! Your bussiness is appreciated! </p>